---
- name: Create EC2 
  hosts: localhost
  gather_facts: no
  vars:
    region: "us-west-2"
    ami_id: "ami-0c587d11c0a52bfbf"  # Example AMI ID (Ubuntu 20.04 LTS)
    instance_type: "t3.micro"
    key_name: "organ-key"  # Replace with your actual SSH key pair name
    security_group_name: "my-sg"
    subnet_id: "subnet-023347d9d4fe3a7ff"  # Replace with your subnet ID

  tasks:
    - name: Create a security group
      amazon.aws.ec2_group:
        name: "{{ security_group_name }}"
        description: "Security group for EC2 instance"
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "0.0.0.0/0"  # SSH access
        state: present
      register: sg

    - name: Create an EC2 instance
      amazon.aws.ec2_instance:
        name: "MyEC2Instance"
        image_id: "{{ ami_id }}"
        instance_type: "{{ instance_type }}"
        key_name: "{{ key_name }}"
        region: "{{ region }}"
        security_groups:
          - "{{ sg.group_name }}"
        subnet_id: "{{ subnet_id }}"
        count: 1
        wait: yes
      register: ec2_instance
