---
- name: Create a Pod in Kubernetes
  hosts: all
  gather_facts: no
  collections:
    - community.kubernetes

  tasks:
    - name: Create a simple nginx pod
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Pod
          metadata:
            name: amit-pod
            namespace: default
          spec:
            containers:
              - name: nginx
                image: nginx:latest
                ports:
                  - containerPort: 80
